services:
  my_sql:
    image: mysql:8.0.32
    container_name: mysql-rest-service
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./data/mysql:/var/lib/mysql:cached
      - ./logs/mysql:/var/log/mysql:cached
      - ./config/mysql/conf-local:/etc/mysql/conf.d:cached
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    links:
      - my_sql:db

  redis:
    image: redis:7.2.4-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass password
